name: panchakarmaflow
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI & responsive
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^1.1.1
  
  # Feature dependencies
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.5
  dio: ^5.8.0
  fluttertoast: ^8.2.14
  fl_chart: ^1.1.1       # updated for Flutter 3.6+
  flutter_slidable: ^4.0.3
  camera: ^0.10.6
  image_picker: ^1.0.5
  permission_handler: ^11.4.0
  record: ^6.0.0
  file_picker: ^8.3.7
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  table_calendar: ^3.1.3
  pay: ^3.2.1
  supabase_flutter: ^2.10.1
  crypto: ^3.0.6
  intl: ^0.20.2           # updated to match Flutter SDK
  pinput: ^5.0.2
  sms_autofill: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
